// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
module.exports = {
  curriculumSidebar: [
    {
      type: 'autogenerated',
      dirName: 'curriculum',
    },
  ],
};

