// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

export default {
  curriculumSidebar: [
    {
      type: 'category',
      label: 'TIER 1 — NOOB',
      items: [{ type: 'autogenerated', dirName: 'curriculum/tier-01-noob' }],
    },
  ],
};


// when ready to unlock another tier:
// {
//  type: 'category',
//  label: 'TIER 2 — BEGINNER',
//  items: [{ type: 'autogenerated', dirName: 'curriculum/tier-02-beginner' }],
// },